data:extend(
{
  {
    type = "fluid",
    name = "naphtha",
    subgroup = "fluid",
    default_temperature = 25,
    base_color = {0.69, 0.55, 0.42},
    flow_color = {0.79, 0.65, 0.52},
    icon = "__outer_moons__/graphics/icons/fluid/naphtha.png",
    order = "a[fluid]-b[oil]-d[naphtha]"
  },
	---
  {
    type = "fluid",
    name = "ammoniacal-solution",
    icon = "__space-age__/graphics/icons/fluid/ammoniacal-solution.png",
    subgroup = "fluid",
    order = "b[new-fluid]-g[aquilo]-a[ammoniacal-solution]",
    default_temperature = -50,
    max_temperature = 100,
    heat_capacity = "0.2kJ",
    base_color = {0, 0.15, 0.4},
    flow_color = {0, 0.35, 0.7},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "ammonia",
    subgroup = "fluid",
    icon = "__space-age__/graphics/icons/fluid/ammonia.png",
    order = "b[new-fluid]-g[aquilo]-b[ammonia]",
    default_temperature = -35,
    max_temperature = -33,
    heat_capacity = "0.2kJ",
    base_color = {0, 0, 0.6},
    flow_color = {0, 0, 0.7},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "fluorine",
    icon = "__space-age__/graphics/icons/fluid/fluorine.png",
    subgroup = "fluid",
    order = "b[new-fluid]-g[aquilo]-c[fluorine]",
    default_temperature = 25,
    heat_capacity = "0.1kJ",
    base_color = {0.0, 0.3, 0.15},
    flow_color = {0.1, 0.7, 0.4},
    gas_temperature = 15,
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "fluoroketone-cold",
    icon = "__space-age__/graphics/icons/fluid/fluoroketone-cold.png",
    subgroup = "fluid",
    order = "b[new-fluid]-g[aquilo]-e[fluoroketone-cold]",
    default_temperature = -150,
    max_temperature = 180,
    heat_capacity = "1kJ",
    base_color = {0.0, 0.3, 0.15},
    flow_color = {0.1, 0.7, 0.4},
  },
  {
    type = "fluid",
    name = "fluoroketone-hot",
    icon = "__space-age__/graphics/icons/fluid/fluoroketone-hot.png",
    subgroup = "fluid",
    order = "b[new-fluid]-g[aquilo]-d[fluoroketone-hot]",
    default_temperature = 180,
    heat_capacity = "1kJ",
    base_color = {0.3, 0.3, 0.10},
    flow_color = {0.4, 0.7, 0.35},
  },
  {
    type = "fluid",
    name = "holmium-solution",
    icon = "__space-age__/graphics/icons/fluid/holmium-solution.png",
    subgroup = "fluid",
    order = "b[new-fluid]-e[fulgora]-b[holmium-solution]",
    default_temperature = 15,
    max_temperature = 2000,
    heat_capacity = "0.01kJ",
    base_color = {0.53, 0.1, 53},
    flow_color = {0.93, 0.68, 0.73},
    auto_barrel = false,
  },
  {
    type = "fluid",
    name = "electrolyte",
    icon = "__space-age__/graphics/icons/fluid/electrolyte.png",
    subgroup = "fluid",
    order = "b[new-fluid]-e[fulgora]-c[electrolyte]",
    default_temperature = 15,
    max_temperature = 500,
    heat_capacity = "0.01kJ",
    base_color = {0.8, 0.01, 0.2},
    flow_color = {0.99, 0.01, 0.3},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "lithium-brine",
    icon = "__space-age__/graphics/icons/fluid/lithium-brine.png",
    subgroup = "fluid",
    order = "b[new-fluid]-g[aquilo]-f[lithium-brine]",
    default_temperature = 15,
    heat_capacity = "0.1kJ",
    base_color = {0.8, 0.85, .8},
    flow_color = {0.6, 0.65, 0.6},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "lava",
    icon = "__space-age__/graphics/icons/fluid/lava.png",
    subgroup = "fluid",
    order = "b[new-fluid]-c[vulcanus]-a[lava]",
    default_temperature = 1500,
    max_temperature = 2000,
    heat_capacity = "0.01kJ",
    base_color = {1, 0.4, 0.1},
    flow_color = {0.3, 0.1, 0},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "molten-iron",
    icon = "__space-age__/graphics/icons/fluid/molten-iron.png",
    subgroup = "fluid",
    order = "b[new-fluid]-c[vulcanus]-a[molten-iron]",
    default_temperature = 1500,
    max_temperature = 2000,
    heat_capacity = "0.01kJ",
    base_color = {0, 0.1, 0.53},
    flow_color = {0.2, 0.68, 0.93},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "molten-copper",
    icon = "__space-age__/graphics/icons/fluid/molten-copper.png",
    subgroup = "fluid",
    order = "b[new-fluid]-c[vulcanus]-b[molten-copper]",
    default_temperature = 1100,
    max_temperature = 2000,
    heat_capacity = "0.01kJ",
    base_color = {0.53, 0.1, 0},
    flow_color = {0.93, 0.68, 0.2},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "thruster-fuel",
    icon = "__space-age__/graphics/icons/fluid/thruster-fuel.png",
    subgroup = "fluid",
    order = "b[new-fluid]-z[space]-a[thruster-fuel]",
    default_temperature = 25,
    fuel_value = "50kJ",
    base_color = {0.53, 0.1, 0},
    flow_color = {0.93, 0.68, 0.2},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "thruster-oxidizer",
    icon = "__space-age__/graphics/icons/fluid/thruster-oxidizer.png",
    subgroup = "fluid",
    order = "b[new-fluid]-z[space]-b[thruster-oxidizer]",
    default_temperature = 25,
    fuel_value = "50kJ",
    base_color = {0.0, 0.1, 0.53},
    flow_color = {0.2, 0.68, 0.93},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "fusion-plasma",
    icon = "__space-age__/graphics/icons/fluid/fusion-plasma.png",
    subgroup = "fluid",
    order = "b[new-fluid]-g[aquilo]-g[fusion-plasma]",
    default_temperature = 1000000,
    max_temperature = 10000000,
    heat_capacity = "25J",
    base_color = {0.0, 0.1, 0.53},
    flow_color = {0.2, 0.68, 0.93},
    auto_barrel = false
  },
  -- AMYZ
  
  {
    type = "fluid",
    name = "saline",
    icon = "__outer_moons__/graphics/icons/fluid/saline.png",
    subgroup = "fluid",
    order = "b[new-fluid]-b[selene]-a[saline]",
    default_temperature = 25,
	gas_temperature = 100,
    heat_capacity = "0.1kJ",
    base_color = {0.52, 0.58, 0.69},
    flow_color = {0.62, 0.68, 0.79},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "chlorine",
    icon = "__outer_moons__/graphics/icons/fluid/chlorine.png",
    subgroup = "fluid",
    order = "b[new-fluid]-b[selene]-b[chlorine]",
    default_temperature = 25,
	gas_temperature = -35,
    heat_capacity = "0.1kJ",
    base_color = {0.36, 0.62, 0.36},
    flow_color = {0.46, 0.72, 0.46},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "red-mud",
    icon = "__outer_moons__/graphics/icons/fluid/red-mud.png",
    subgroup = "fluid",
    order = "b[new-fluid]-b[selene]-c[red-mud]",
    default_temperature = 25,
	gas_temperature = 100,
    heat_capacity = "0.1kJ",
    base_color = {0.52, 0.58, 0.69},
    flow_color = {0.62, 0.68, 0.79},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "oxygen",
    icon = "__outer_moons__/graphics/icons/fluid/oxygen.png",
    subgroup = "fluid",
    order = "b[new-fluid]-b[selene]-e[oxygen]",
    default_temperature = 25,
	gas_temperature = -180,
    heat_capacity = "0.1kJ",
    base_color = {0.9, 0.9, 0.9},
    flow_color = {0.95, 0.95, 0.95},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "ethylene",
    icon = "__outer_moons__/graphics/icons/fluid/ethylene.png",
    subgroup = "fluid",
    order = "b[new-fluid]-b[selene]-d[ethylene]",
    default_temperature = 25,
    heat_capacity = "0.1kJ",
	default_temperature = 25,
    base_color = {0.4, 0.2, 0.4},
    flow_color = {0.8, 0.4, 0.8},
    auto_barrel = false
  },
  --Gleba
  {
    type = "fluid",
    name = "slipgoo",
    icon = "__outer_moons__/graphics/icons/fluid/slipgoo.png",
    subgroup = "fluid",
    order = "b[new-fluid]-d[gleba]-a[slipgoo]",
    default_temperature = 25,
    heat_capacity = "0.1kJ",
	default_temperature = 25,
    base_color = {0.4, 0.2, 0.4},
    flow_color = {0.8, 0.4, 0.8},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "mawslush",
    icon = "__outer_moons__/graphics/icons/fluid/mawslush.png",
    subgroup = "fluid",
    order = "b[new-fluid]-d[gleba]-b[mawslush]",
    default_temperature = 25,
    heat_capacity = "0.1kJ",
	default_temperature = 25,
    base_color = {0.4, 0.2, 0.4},
    flow_color = {0.8, 0.4, 0.8},
    auto_barrel = false
  },
  {
    type = "fluid",
    name = "bioslurry",
    icon = "__outer_moons__/graphics/icons/fluid/bioslurry.png",
    subgroup = "fluid",
    order = "b[new-fluid]-d[gleba]-c[bioslurry]",
    default_temperature = 25,
    heat_capacity = "0.1kJ",
	default_temperature = 25,
    base_color = {0.4, 0.2, 0.4},
    flow_color = {0.8, 0.4, 0.8},
    --auto_barrel = false
  },
  --Fulgora
  {
    type = "fluid",
    name = "sludge",
    icon = "__outer_moons__/graphics/icons/fluid/fulgoran-sludge.png",
    subgroup = "fluid",
    order = "b[new-fluid]-e[fulgora]-a[sludge]",
    default_temperature = 5,
    --max_temperature = 2000,
    heat_capacity = "0.1kJ",
    base_color = {r = 0.24, g = 0.16, b = 0.16},
    flow_color = {r = 0.08, g = 0.08, b = 0.08},
    auto_barrel = false,
  },
})
