local item_sounds = require("__base__.prototypes.item_sounds")
local space_age_item_sounds = require("__space-age__.prototypes.item_sounds")
local meld = require("meld")

---Creates a basic item
---@param name string name of the item
---@param stack_size integer? The stack size of the item
---@param weight integer? The weight of the item
---@param glow boolean? Does this item glow?
---@param size int? The size of the icon image
---@param extra table? Extra parameters to set?
---@return table
local function quick_item(name, stack_size, weight, glow, extra)
    return meld({
        type = "item",
        name = name,
        subgroup = "intermediate-product",
        stack_size = stack_size or 100,
        icon = "__outer_moons__/graphics/icons/" .. name .. ".png",
        pictures = {
            size = 64,
            filename = "__outer_moons__/graphics/icons/" .. name .. ".png",
            scale = 0.5,
            draw_as_glow = glow or false,
        },
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        weight = weight or (2 * kg)
    }, extra or {})
end


data:extend({
	-- Nauvis
	{
        type = "item",
        name = "silicon-ore",
        group = "intermediate-products",
        icon = "__outer_moons__/graphics/icons/silicon-ore.png",
		pictures =
		{
		  { size = 64, filename = "__outer_moons__/graphics/icons/silicon-ore.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/silicon-ore-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/silicon-ore-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/silicon-ore-4.png", scale = 0.5, mipmap_count = 4 },
		},
        subgroup = "raw-resource",
		default_import_location = "nauvis",
		order = "g[silicon-ore]",
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        stack_size = 50,
        weight = 2 * kg
    },
	{
		type = "item",
		name = "silicon-plate",		
        group = "intermediate-products",
		icon = "__outer_moons__/graphics/icons/silicon-plate.png",
		subgroup = "raw-material",
		order = "a[smelting]-d[silicon-plate]",
		inventory_move_sound = item_sounds.metal_small_inventory_move,
		pick_sound = item_sounds.metal_small_inventory_pickup,
		drop_sound = item_sounds.metal_small_inventory_move,
		stack_size = 100,
		weight = 10 * kg,
	},
	--Rocket parts
	{
		type = "item",
		name = "rocket-part-new",
		icon = "__outer_moons__/graphics/icons/rocket-part-new.png",
		subgroup = "intermediate-product",
		order = "d[rocket-parts]-c[rocket-part-new]",
		inventory_move_sound = item_sounds.mechanical_inventory_move,
		pick_sound = item_sounds.mechanical_inventory_pickup,
		drop_sound = item_sounds.mechanical_inventory_move,
		stack_size = 20,
		weight = 20*kg,
	},
	-- Selene
	{
        type = "item",
        name = "metallic-regolith",
        group = "intermediate-products",
        icon = "__outer_moons__/graphics/icons/regolith.png",
        pictures =
        {
            size = 64,
            filename = "__outer_moons__/graphics/icons/regolith.png",
            scale = 0.5,
            mipmap_count = 4,
        },
        subgroup = "selene-resources",
		default_import_location = "selene",
        color_hint = { text = "I" },
        order = "a[regolith]",
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        stack_size = 200,
        weight = 1 * kg
    },
	{
        type = "item",
        name = "aluminum-ore",
        group = "intermediate-products",
        icon = "__outer_moons__/graphics/icons/aluminum-ore.png",
		pictures =
		{
		  { size = 64, filename = "__outer_moons__/graphics/icons/aluminum-ore.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/aluminum-ore-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/aluminum-ore-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/aluminum-ore-4.png", scale = 0.5, mipmap_count = 4 },
		},
        subgroup = "selene-resources",
		default_import_location = "selene",
        order = "b[aluminum-ore]",
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        stack_size = 50,
        weight = 5 * kg
    },
    {
        type = "item",
        name = "titanium-ore",
        group = "intermediate-products",
        icon = "__outer_moons__/graphics/icons/titanium-ore.png",
        pictures =
		{
		  { size = 64, filename = "__outer_moons__/graphics/icons/titanium-ore.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/titanium-ore-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/titanium-ore-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/titanium-ore-4.png", scale = 0.5, mipmap_count = 4 },
		},
        subgroup = "selene-resources",
		default_import_location = "selene",
        order = "c[titanium-ore]",
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        stack_size = 50,
        weight = 10 * kg
    },
	{
		type = "item",
		name = "titanium-plate",		
        group = "intermediate-products",
		icon = "__outer_moons__/graphics/icons/titanium-plate.png",
		subgroup = "selene-resources",
		order = "h[titanium-plate]",
		inventory_move_sound = item_sounds.metal_small_inventory_move,
		pick_sound = item_sounds.metal_small_inventory_pickup,
		drop_sound = item_sounds.metal_small_inventory_move,
		stack_size = 100,
		weight = 10 * kg,
	},
	{
		type = "item",
		name = "lye",		
        group = "intermediate-products",
		icon = "__outer_moons__/graphics/icons/lye.png",
		subgroup = "selene-resources",
		order = "d[lye]",
		inventory_move_sound = item_sounds.sulfur_inventory_move,
		pick_sound = item_sounds.resource_inventory_pickup,
		drop_sound = item_sounds.sulfur_inventory_move,
		stack_size = 200,
		weight = 1 * kg,
	},
	{
		type = "item",
		name = "gibbsite",		
        group = "intermediate-products",
		icon = "__outer_moons__/graphics/icons/gibbsite.png",
		subgroup = "selene-resources",
		order = "e[gibbsite]",
		inventory_move_sound = item_sounds.sulfur_inventory_move,
		pick_sound = item_sounds.resource_inventory_pickup,
		drop_sound = item_sounds.sulfur_inventory_move,
		stack_size = 200,
		weight = 1 * kg,
	},
	{
		type = "item",
		name = "alumina",		
        group = "intermediate-products",
		icon = "__outer_moons__/graphics/icons/alumina.png",
		subgroup = "selene-resources",
		order = "f[alumina]",
		inventory_move_sound = item_sounds.sulfur_inventory_move,
		pick_sound = item_sounds.resource_inventory_pickup,
		drop_sound = item_sounds.sulfur_inventory_move,
		stack_size = 200,
		weight = 1 * kg,
	},
	{
		type = "item",
		name = "aluminum-plate",		
        group = "selene-resources",
		icon = "__outer_moons__/graphics/icons/aluminum-plate.png",
		subgroup = "selene-resources",
		order = "g[aluminum-plate]",
		inventory_move_sound = item_sounds.metal_small_inventory_move,
		pick_sound = item_sounds.metal_small_inventory_pickup,
		drop_sound = item_sounds.metal_small_inventory_move,
		stack_size = 100,
		weight = 1 * kg,
	},
	--Gleba	
	-- seeds
	{
        type = "item",
        name = "phosphate",
        group = "intermediate-products",
        icon = "__outer_moons__/graphics/icons/phosphate.png",
		pictures =
		{
		  { size = 64, filename = "__outer_moons__/graphics/icons/phosphate.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/phosphate-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/phosphate-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/phosphate-4.png", scale = 0.5, mipmap_count = 4 },
		},
        subgroup = "agriculture-products",
		order = "a[organic-processing]-a[phosphate]",
		default_import_location = "gleba",
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        stack_size = 50,
        weight = 5 * kg
    },
	{
		type = "item",
		name = "funneltrunk-seed",
		localised_name = {"item-name.funneltrunk-seed"},
		icon = "__outer_moons__/graphics/icons/funneltrunk-seed.png",
		pictures =
		{
		  { size = 64, filename = "__outer_moons__/graphics/icons/funneltrunk-seed.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/funneltrunk-seed-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/funneltrunk-seed-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/funneltrunk-seed-4.png", scale = 0.5, mipmap_count = 4 },
		},
		subgroup = "agriculture-processes",
		order = "b[seeds]-d[funneltrunk-seed]",
		plant_result = "funneltrunk-plant",
		place_result = "funneltrunk-plant",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		stack_size = 10,
		default_import_location = "gleba",
		weight = 10 * kg,
		fuel_category = "chemical",
		fuel_value = "4MJ"
	},
	{
		type = "item",
		name = "slipstack-seed",
		localised_name = {"item-name.slipstack-seed"},
		icon = "__outer_moons__/graphics/icons/slipstack-seed.png",
		pictures =
		{
		  { size = 64, filename = "__outer_moons__/graphics/icons/slipstack-seed.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/slipstack-seed-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/slipstack-seed-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/slipstack-seed-4.png", scale = 0.5, mipmap_count = 4 },
		},
		subgroup = "agriculture-processes",
		order = "b[seeds]-a[slipstack-seed]",
		plant_result = "slipstack-plant",
		place_result = "slipstack-plant",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		stack_size = 10,
		default_import_location = "gleba",
		weight = 10 * kg,
		fuel_category = "chemical",
		fuel_value = "4MJ"
	},
	{
		type = "item",
		name = "yumako-seed",
		localised_name = {"item-name.yumako-seed"},
		icon = "__space-age__/graphics/icons/yumako-seed.png",
		pictures =
		{
		  { size = 64, filename = "__space-age__/graphics/icons/yumako-seed-1.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__space-age__/graphics/icons/yumako-seed-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__space-age__/graphics/icons/yumako-seed-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__space-age__/graphics/icons/yumako-seed-4.png", scale = 0.5, mipmap_count = 4 },
		},
		subgroup = "agriculture-processes",
		order = "b[seeds]-f[yumako-seed]",
		plant_result = "yumako-tree",
		place_result = "yumako-tree",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		stack_size = 10,
		default_import_location = "gleba",
		weight = 10 * kg,
		fuel_category = "chemical",
		fuel_value = "4MJ"
	},
	{
		type = "item",
		name = "lickmaw-seed",
		localised_name = {"item-name.lickmaw-seed"},
		icon = "__outer_moons__/graphics/icons/lickmaw-seed.png",
		pictures =
		{
		  { size = 64, filename = "__outer_moons__/graphics/icons/lickmaw-seed.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/lickmaw-seed-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/lickmaw-seed-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/lickmaw-seed-4.png", scale = 0.5, mipmap_count = 4 },
		},
		subgroup = "agriculture-processes",
		order = "b[seeds]-e[lickmaw-seed]",
		plant_result = "lickmaw-plant",
		place_result = "lickmaw-plant",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		stack_size = 10,
		default_import_location = "gleba",
		weight = 10 * kg,
		fuel_category = "chemical",
		fuel_value = "4MJ"
	},
	{
		type = "item",
		name = "stingfrond-seed",
		localised_name = {"item-name.stingfrond-seed"},
		icon = "__outer_moons__/graphics/icons/stingfrond-seed.png",
		pictures =
		{
		  { size = 64, filename = "__outer_moons__/graphics/icons/stingfrond-seed.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/stingfrond-seed-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/stingfrond-seed-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/stingfrond-seed-4.png", scale = 0.5, mipmap_count = 4 },
		},
		subgroup = "agriculture-processes",
		order = "b[seeds]-h[stingfrond-seed]",
		plant_result = "stingfrond-plant",
		place_result = "stingfrond-plant",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		stack_size = 10,
		default_import_location = "gleba",
		weight = 10 * kg,
		fuel_category = "chemical",
		fuel_value = "4MJ"
	},
	{
		type = "item",
		name = "cuttlepop-seed",
		localised_name = {"item-name.cuttlepop-seed"},
		icon = "__outer_moons__/graphics/icons/cuttlepop-seed.png",
		pictures =
		{
		  { size = 64, filename = "__outer_moons__/graphics/icons/cuttlepop-seed.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/cuttlepop-seed-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/cuttlepop-seed-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/cuttlepop-seed-4.png", scale = 0.5, mipmap_count = 4 },
		},
		subgroup = "agriculture-processes",
		order = "b[seeds]-c[cuttlepop-seed]",
		plant_result = "cuttlepop-plant",
		place_result = "cuttlepop-plant",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		stack_size = 10,
		default_import_location = "gleba",
		weight = 10 * kg,
		fuel_category = "chemical",
		fuel_value = "4MJ"
	},
	{
		type = "item",
		name = "boompuff-seed",
		localised_name = {"item-name.boompuff-seed"},
		icon = "__outer_moons__/graphics/icons/boompuff-seed.png",
		pictures =
		{
		  { size = 64, filename = "__outer_moons__/graphics/icons/boompuff-seed.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/boompuff-seed-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/boompuff-seed-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/boompuff-seed-4.png", scale = 0.5, mipmap_count = 4 },
		},
		subgroup = "agriculture-processes",
		order = "b[seeds]-g[boompuff-seed]",
		plant_result = "boompuff-plant",
		place_result = "boompuff-plant",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		stack_size = 10,
		default_import_location = "gleba",
		weight = 10 * kg,
		fuel_category = "chemical",
		fuel_value = "4MJ"
	},
	{
		type = "item",
		name = "sunnycomb-seed",
		localised_name = {"item-name.sunnycomb-seed"},
		icon = "__outer_moons__/graphics/icons/sunnycomb-seed.png",
		pictures =
		{
		  { size = 64, filename = "__outer_moons__/graphics/icons/sunnycomb-seed.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/sunnycomb-seed-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/sunnycomb-seed-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/sunnycomb-seed-4.png", scale = 0.5, mipmap_count = 4 },
		},
		subgroup = "agriculture-processes",
		order = "b[seeds]-b[sunnycomb-seed]",
		plant_result = "sunnycomb-plant",
		place_result = "sunnycomb-plant",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		stack_size = 10,
		default_import_location = "gleba",
		weight = 10 * kg,
		fuel_category = "chemical",
		fuel_value = "4MJ"
	},
	
	
	-- harvestables
	{
		type = "capsule",
		name = "funnelwood",
		icon = "__outer_moons__/graphics/icons/funnelwood-1.png",
		pictures =
		{
		  { size = 64, filename = "__outer_moons__/graphics/icons/funnelwood-1.png",   scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/funnelwood-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/funnelwood-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/funnelwood-4.png", scale = 0.5, mipmap_count = 4 }
		},
		subgroup = "agriculture-processes",
		order = "a[agriculture]-d[funnelwood]",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		fuel_category = "chemical",
		fuel_value = "2MJ",
		stack_size = 50,
		default_import_location = "gleba",
		weight = 1 * kg,
		spoil_ticks = 60 * minute,
		spoil_result = "spoilage",
		capsule_action = item_effects.yumako_regen
	},
	{
		type = "capsule",
		name = "slipstack-polyp",
		icon = "__outer_moons__/graphics/icons/slipstack-polyp-1.png",
		pictures =
		{
		  { size = 64, filename = "__outer_moons__/graphics/icons/slipstack-polyp-1.png",   scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/slipstack-polyp-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/slipstack-polyp-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/slipstack-polyp-4.png", scale = 0.5, mipmap_count = 4 }
		},
		subgroup = "agriculture-processes",
		order = "a[agriculture]-a[slipstack-polyp]",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		fuel_category = "chemical",
		fuel_value = "2MJ",
		stack_size = 50,
		default_import_location = "gleba",
		weight = 1 * kg,
		spoil_ticks = 60 * minute,
		spoil_result = "spoilage",
		capsule_action = item_effects.yumako_regen
	},
	{
		type = "capsule",
		name = "yumako",
		icon = "__space-age__/graphics/icons/yumako.png",
		pictures =
		{
		  { size = 64, filename = "__space-age__/graphics/icons/yumako.png",   scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__space-age__/graphics/icons/yumako-1.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__space-age__/graphics/icons/yumako-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__space-age__/graphics/icons/yumako-3.png", scale = 0.5, mipmap_count = 4 }
		},
		subgroup = "agriculture-processes",
		order = "a[agriculture]-f[yumako]",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		fuel_category = "chemical",
		fuel_value = "2MJ",
		stack_size = 50,
		default_import_location = "gleba",
		weight = 1 * kg,
		spoil_ticks = 60 * minute,
		spoil_result = "spoilage",
		capsule_action = item_effects.yumako_regen
	},
	{
		type = "capsule",
		name = "mawpouch",
		icon = "__outer_moons__/graphics/icons/mawpouch-1.png",
		pictures =
		{
		  { size = 64, filename = "__outer_moons__/graphics/icons/mawpouch-1.png",   scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/mawpouch-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/mawpouch-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/mawpouch-4.png", scale = 0.5, mipmap_count = 4 }
		},
		subgroup = "agriculture-processes",
		order = "a[agriculture]-e[mawpouch]",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		fuel_category = "chemical",
		fuel_value = "2MJ",
		stack_size = 50,
		default_import_location = "gleba",
		weight = 1 * kg,
		spoil_ticks = 60 * minute,
		spoil_result = "spoilage",
		capsule_action = item_effects.yumako_regen
	},
	{
		type = "capsule",
		name = "cuttlepod",
		icon = "__outer_moons__/graphics/icons/cuttlepod-1.png",
		pictures =
		{
		  { size = 64, filename = "__outer_moons__/graphics/icons/cuttlepod-1.png",   scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/cuttlepod-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/cuttlepod-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/cuttlepod-4.png", scale = 0.5, mipmap_count = 4 }
		},
		subgroup = "agriculture-processes",
		order = "a[agriculture]-c[cuttlepod]",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		fuel_category = "chemical",
		fuel_value = "2MJ",
		stack_size = 50,
		default_import_location = "gleba",
		weight = 1 * kg,
		spoil_ticks = 60 * minute,
		spoil_result = "spoilage",
		capsule_action = item_effects.yumako_regen
	},
	{
		type = "capsule",
		name = "frondstalk",
		icon = "__outer_moons__/graphics/icons/frondstalk-1.png",
		pictures =
		{
		  { size = 64, filename = "__outer_moons__/graphics/icons/frondstalk-1.png",   scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/frondstalk-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/frondstalk-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/frondstalk-4.png", scale = 0.5, mipmap_count = 4 }
		},
		subgroup = "agriculture-processes",
		order = "a[agriculture]-h[frondstalk]",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		fuel_category = "chemical",
		fuel_value = "2MJ",
		stack_size = 50,
		default_import_location = "gleba",
		weight = 1 * kg,
		spoil_ticks = 60 * minute,
		spoil_result = "spoilage",
		capsule_action = item_effects.yumako_regen
	},
	{
		type = "capsule",
		name = "boompuff-bulb",
		icon = "__outer_moons__/graphics/icons/boompuff-bulb-1.png",
		pictures =
		{
		  { size = 64, filename = "__outer_moons__/graphics/icons/boompuff-bulb-1.png",   scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/boompuff-bulb-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/boompuff-bulb-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/boompuff-bulb-4.png", scale = 0.5, mipmap_count = 4 }
		},
		subgroup = "agriculture-processes",
		order = "a[agriculture]-g[boompuff-bulb]",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		fuel_category = "chemical",
		fuel_value = "2MJ",
		stack_size = 50,
		default_import_location = "gleba",
		weight = 1 * kg,
		spoil_ticks = 60 * minute,
		spoil_result = "spoilage",
		capsule_action = item_effects.yumako_regen
	},
	{
		type = "capsule",
		name = "sunnycomb",
		icon = "__outer_moons__/graphics/icons/sunnycomb-1.png",
		pictures =
		{
		  { size = 64, filename = "__outer_moons__/graphics/icons/sunnycomb-1.png",   scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/sunnycomb-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/sunnycomb-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__outer_moons__/graphics/icons/sunnycomb-4.png", scale = 0.5, mipmap_count = 4 }
		},
		subgroup = "agriculture-processes",
		order = "a[agriculture]-b[sunnycomb]",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		fuel_category = "chemical",
		fuel_value = "2MJ",
		stack_size = 50,
		default_import_location = "gleba",
		weight = 1 * kg,
		spoil_ticks = 60 * minute,
		spoil_result = "spoilage",
		capsule_action = item_effects.yumako_regen
	},
	-- processed
	{
		type = "capsule",
		name = "funnelbranch",
		icon = "__outer_moons__/graphics/icons/funnelbranch.png",
		subgroup = "agriculture-products",
		order = "a[organic-processing]-c[funnelbranch]",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		fuel_category = "chemical",
		fuel_value = "1MJ",
		stack_size = 100,
		default_import_location = "gleba",
		spoil_ticks = 3 * minute,
		spoil_result = "spoilage",
		weight = 0.5 * kg,
		capsule_action = item_effects.yumako_regen
	},
	{
		type = "capsule",
		name = "yumako-mash",
		icon = "__space-age__/graphics/icons/yumako-mash.png",
		subgroup = "agriculture-products",
		order = "a[organic-processing]-e[yumako-mash]",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		fuel_category = "chemical",
		fuel_value = "1MJ",
		stack_size = 100,
		default_import_location = "gleba",
		spoil_ticks = 3 * minute,
		spoil_result = "spoilage",
		weight = 0.5 * kg,
		capsule_action = item_effects.yumako_regen
	},
	{
		type = "capsule",
		name = "jelly",
		icon = "__space-age__/graphics/icons/jelly.png",
		subgroup = "agriculture-products",
		order = "a[organic-processing]-b[jelly]",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		fuel_category = "chemical",
		fuel_value = "1MJ",
		stack_size = 100,
		default_import_location = "gleba",
		spoil_ticks = 4 * minute,
		spoil_result = "spoilage",
		weight = 0.5 * kg,
		capsule_action = item_effects.jellynut_speed
	},
	{
		type = "capsule",
		name = "frondstrand",
		icon = "__outer_moons__/graphics/icons/frondstrand.png",
		subgroup = "agriculture-products",
		order = "a[organic-processing]-g[frondstrand]",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		fuel_category = "chemical",
		fuel_value = "1MJ",
		stack_size = 100,
		default_import_location = "gleba",
		spoil_ticks = 4 * minute,
		spoil_result = "spoilage",
		weight = 0.5 * kg,
		capsule_action = item_effects.yumako_regen
	},
	{
		type = "capsule",
		name = "boompowder",
		icon = "__outer_moons__/graphics/icons/boompowder.png",
		subgroup = "agriculture-products",
		order = "a[organic-processing]-f[boompowder]",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		fuel_category = "chemical",
		fuel_value = "1MJ",
		stack_size = 100,
		default_import_location = "gleba",
		spoil_ticks = 3 * minute,
		spoil_result = "spoilage",
		weight = 0.5 * kg,
		capsule_action = item_effects.yumako_regen
	},
	{
		type = "capsule",
		name = "sunnylattice",
		icon = "__outer_moons__/graphics/icons/sunnylattice.png",
		subgroup = "agriculture-products",
		order = "a[organic-processing]-a[sunnylattice]",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		fuel_category = "chemical",
		fuel_value = "1MJ",
		stack_size = 100,
		default_import_location = "gleba",
		spoil_ticks = 5 * minute,
		spoil_result = "spoilage",
		weight = 0.5 * kg,
		capsule_action = item_effects.yumako_regen
	},
	{
		type = "capsule",
		name = "bioflux",
		icon = "__space-age__/graphics/icons/bioflux.png",
		subgroup = "agriculture-products",
		order = "b[organic-processing]-h[bioflux]",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		fuel_category = "food",
		fuel_value = "6MJ",
		stack_size = 100,
		default_import_location = "gleba",
		spoil_ticks = 2 * hour,
		spoil_result = "spoilage",
		weight = 1 * kg,
		capsule_action = item_effects.bioflux_speed_and_regen
	},
	{
        type = "item",
        name = "potassium-salt",
        group = "intermediate-products",
        icon = "__outer_moons__/graphics/icons/potassium-salt.png",
        subgroup = "agriculture-products",
		default_import_location = "gleba",
        order = "a[organic-processing]-d[potassium-salt]",
        inventory_move_sound = item_sounds.sulfur_inventory_move,
		pick_sound = item_sounds.resource_inventory_pickup,
		drop_sound = item_sounds.sulfur_inventory_move,
        stack_size = 200,
        weight = 1 * kg
    },
	{
        type = "item",
        name = "niter",
        group = "intermediate-products",
        icon = "__outer_moons__/graphics/icons/niter.png",
        subgroup = "agriculture-products",
		default_import_location = "gleba",
        order = "b[organic-processing]-d[niter]",
        inventory_move_sound = item_sounds.sulfur_inventory_move,
		pick_sound = item_sounds.resource_inventory_pickup,
		drop_sound = item_sounds.sulfur_inventory_move,
        stack_size = 200,
        weight = 1 * kg
    },
	--
	{
        type = "item",
        name = "fertilizer",
        group = "intermediate-products",
        icon = "__outer_moons__/graphics/icons/fertilizer.png",
        subgroup = "agriculture-products",
		default_import_location = "gleba",
        order = "b[organic-products]-a[fertilizer]",
        inventory_move_sound = item_sounds.agriculture_inventory_move,
		pick_sound = item_sounds.agriculture_inventory_pickup,
		drop_sound = item_sounds.agriculture_inventory_move,
        stack_size = 100,
        weight = 2 * kg
    },
	{
		type = "item",
		name = "artificial-yumako-soil",
		icon = "__outer_moons__/graphics/icons/artificial-virid-soil.png",
		subgroup = "terrain",
		order = "c[landfill]-c[artificial]",
		inventory_move_sound = item_sounds.landfill_inventory_move,
		pick_sound = item_sounds.landfill_inventory_pickup,
		drop_sound = item_sounds.landfill_inventory_move,
		stack_size = 100,
		default_import_location = "gleba",
		place_as_tile =
		{
		  result = "artificial-yumako-soil",
		  condition_size = 1,
		  condition = {layers={}},
		  tile_condition = {
			"wetland-light-green-slime",
			"wetland-green-slime",
			"wetland-yumako",
			"lowland-olive-blubber",
			"lowland-olive-blubber-2",
			"lowland-olive-blubber-3",
			"lowland-brown-blubber",
			"lowland-pale-green",
			"natural-yumako-soil"
		  }
		}
	},
	{
		type = "item",
		name = "overgrowth-yumako-soil",
		icon = "__outer_moons__/graphics/icons/overgrowth-virid-soil.png",
		subgroup = "terrain",
		order = "c[landfill]-c[overgrowth]",
		inventory_move_sound = item_sounds.landfill_inventory_move,
		pick_sound = item_sounds.landfill_inventory_pickup,
		drop_sound = item_sounds.landfill_inventory_move,
		stack_size = 100,
		default_import_location = "gleba",
		place_as_tile =
		{
		  result = "overgrowth-yumako-soil",
		  condition_size = 1,
		  condition = {layers={}},
		  tile_condition = { 
			"wetland-light-green-slime",
			"wetland-green-slime",
			"wetland-yumako",
			"lowland-olive-blubber",
			"lowland-olive-blubber-2",
			"lowland-olive-blubber-3",
			"lowland-brown-blubber",
			"lowland-pale-green",
			"natural-yumako-soil",
			"artificial-yumako-soil",
			"wetland-pink-tentacle",
			"wetland-red-tentacle",
			"wetland-jellynut",
			"lowland-red-vein",
			"lowland-red-vein-2",
			"lowland-red-vein-3",
			"lowland-red-vein-4",
			"lowland-red-vein-dead",
			"lowland-red-infection",
			"lowland-cream-red",
			"lowland-cream-cauliflower",
			"lowland-cream-cauliflower-2",
			"natural-jellynut-soil",
			"artificial-jellynut-soil",
			"midland-yellow-crust",
			"midland-yellow-crust-2",
			"midland-yellow-crust-3",
			"midland-yellow-crust-4",
			"artificial-ochre-soil",
			"lowland-dead-skin",
		    "lowland-dead-skin-2",
			"lowland-cream-cauliflower",
		    "lowland-cream-cauliflower-2",
		    "midland-cracked-lichen-dark",
		    "highland-dark-rock",
		    "artificial-cerulean-soil",
			"wetland-light-dead-skin",
		    "wetland-dead-skin",
		    "wetland-blue-slime",
		    "lowland-cream-cauliflower",
		    "lowland-cream-cauliflower-2",
			"artificial-cuticle-soil",
			"gleba-deep-lake",
			"highland-dark-rock-2",
			"highland-yellow-rock",
		  }
		}
	},
	{
		type = "item",
		name = "artificial-jellynut-soil",
		icon = "__outer_moons__/graphics/icons/artificial-sanguine-soil.png",
		subgroup = "terrain",
		order = "c[landfill]-d[artificial]",
		inventory_move_sound = item_sounds.landfill_inventory_move,
		pick_sound = item_sounds.landfill_inventory_pickup,
		drop_sound = item_sounds.landfill_inventory_move,
		stack_size = 100,
		default_import_location = "gleba",
		place_as_tile =
		{
		  result = "artificial-jellynut-soil",
		  condition_size = 1,
		  condition = {layers={}},
		   tile_condition = {
			"wetland-pink-tentacle",
			"wetland-red-tentacle",
			"wetland-jellynut",
			"lowland-red-vein",
			"lowland-red-vein-2",
			"lowland-red-vein-3",
			"lowland-red-vein-4",
			"lowland-red-vein-dead",
			"lowland-red-infection",
			"lowland-cream-red",
			"lowland-cream-cauliflower",
			"lowland-cream-cauliflower-2",
			"natural-jellynut-soil",
		  }
		}
	},
	{
		type = "item",
		name = "overgrowth-jellynut-soil",
		icon = "__outer_moons__/graphics/icons/overgrowth-sanguine-soil.png",
		subgroup = "terrain",
		order = "c[landfill]-d[overgrowth]",
		inventory_move_sound = item_sounds.landfill_inventory_move,
		pick_sound = item_sounds.landfill_inventory_pickup,
		drop_sound = item_sounds.landfill_inventory_move,
		stack_size = 100,
		default_import_location = "gleba",
		place_as_tile =
		{
		  result = "overgrowth-jellynut-soil",
		  condition_size = 1,
		  condition = {layers={}},
		  tile_condition = { 
			"wetland-light-green-slime",
			"wetland-green-slime",
			"wetland-yumako",
			"lowland-olive-blubber",
			"lowland-olive-blubber-2",
			"lowland-olive-blubber-3",
			"lowland-brown-blubber",
			"lowland-pale-green",
			"natural-yumako-soil",
			"artificial-yumako-soil",
			"wetland-pink-tentacle",
			"wetland-red-tentacle",
			"wetland-jellynut",
			"lowland-red-vein",
			"lowland-red-vein-2",
			"lowland-red-vein-3",
			"lowland-red-vein-4",
			"lowland-red-vein-dead",
			"lowland-red-infection",
			"lowland-cream-red",
			"lowland-cream-cauliflower",
			"lowland-cream-cauliflower-2",
			"natural-jellynut-soil",
			"artificial-jellynut-soil",
			"midland-yellow-crust",
			"midland-yellow-crust-2",
			"midland-yellow-crust-3",
			"midland-yellow-crust-4",
			"artificial-ochre-soil",
			"lowland-dead-skin",
		    "lowland-dead-skin-2",
			"lowland-cream-cauliflower",
		    "lowland-cream-cauliflower-2",
		    "midland-cracked-lichen-dark",
		    "highland-dark-rock",
		    "artificial-cerulean-soil",
			"wetland-light-dead-skin",
		    "wetland-dead-skin",
		    "wetland-blue-slime",
		    "lowland-cream-cauliflower",
		    "lowland-cream-cauliflower-2",
			"artificial-cuticle-soil",
			"gleba-deep-lake",
			"highland-dark-rock-2",
			"highland-yellow-rock",
		  }
		}
	},
	{
		type = "item",
		name = "artificial-ochre-soil",
		icon = "__outer_moons__/graphics/icons/artificial-ochre-soil.png",
		subgroup = "terrain",
		order = "c[landfill]-e[artificial]",
		inventory_move_sound = item_sounds.landfill_inventory_move,
		pick_sound = item_sounds.landfill_inventory_pickup,
		drop_sound = item_sounds.landfill_inventory_move,
		stack_size = 100,
		default_import_location = "gleba",
		place_as_tile =
		{
		  result = "artificial-ochre-soil",
		  condition_size = 1,
		  condition = {layers={}},
		  tile_condition = {
		    "midland-yellow-crust",
			"midland-yellow-crust-2",
			"midland-yellow-crust-3",
			"midland-yellow-crust-4"
		  }
		}
	},
	{
		type = "item",
		name = "overgrowth-ochre-soil",
		icon = "__outer_moons__/graphics/icons/overgrowth-ochre-soil.png",
		subgroup = "terrain",
		order = "c[landfill]-e[overgrowth]",
		inventory_move_sound = item_sounds.landfill_inventory_move,
		pick_sound = item_sounds.landfill_inventory_pickup,
		drop_sound = item_sounds.landfill_inventory_move,
		stack_size = 100,
		default_import_location = "gleba",
		place_as_tile =
		{
		  result = "overgrowth-ochre-soil",
		  condition_size = 1,
		  condition = {layers={}},
		  tile_condition = { 
			"wetland-light-green-slime",
			"wetland-green-slime",
			"wetland-yumako",
			"lowland-olive-blubber",
			"lowland-olive-blubber-2",
			"lowland-olive-blubber-3",
			"lowland-brown-blubber",
			"lowland-pale-green",
			"natural-yumako-soil",
			"artificial-yumako-soil",
			"wetland-pink-tentacle",
			"wetland-red-tentacle",
			"wetland-jellynut",
			"lowland-red-vein",
			"lowland-red-vein-2",
			"lowland-red-vein-3",
			"lowland-red-vein-4",
			"lowland-red-vein-dead",
			"lowland-red-infection",
			"lowland-cream-red",
			"lowland-cream-cauliflower",
			"lowland-cream-cauliflower-2",
			"natural-jellynut-soil",
			"artificial-jellynut-soil",
			"midland-yellow-crust",
			"midland-yellow-crust-2",
			"midland-yellow-crust-3",
			"midland-yellow-crust-4",
			"artificial-ochre-soil",
			"lowland-dead-skin",
		    "lowland-dead-skin-2",
			"lowland-cream-cauliflower",
		    "lowland-cream-cauliflower-2",
		    "midland-cracked-lichen-dark",
		    "highland-dark-rock",
		    "artificial-cerulean-soil",
			"wetland-light-dead-skin",
		    "wetland-dead-skin",
		    "wetland-blue-slime",
		    "lowland-cream-cauliflower",
		    "lowland-cream-cauliflower-2",
			"artificial-cuticle-soil",
			"gleba-deep-lake",
			"highland-dark-rock-2",
			"highland-yellow-rock",
		  }
		}
	},
	{
		type = "item",
		name = "artificial-cerulean-soil",
		icon = "__outer_moons__/graphics/icons/artificial-cerulean-soil.png",
		subgroup = "terrain",
		order = "c[landfill]-f[artificial]",
		inventory_move_sound = item_sounds.landfill_inventory_move,
		pick_sound = item_sounds.landfill_inventory_pickup,
		drop_sound = item_sounds.landfill_inventory_move,
		stack_size = 100,
		default_import_location = "gleba",
		place_as_tile =
		{
		  result = "artificial-cerulean-soil",
		  condition_size = 1,
		  condition = {layers={}},
		  tile_condition = {
		    "midland-turquoise-bark",
		    "midland-turquoise-bark-2",
		    "midland-cracked-lichen",
		    "midland-cracked-lichen-dull",
		    "midland-cracked-lichen-dark",
		    "highland-dark-rock"
		  }
		}
	},
	{
		type = "item",
		name = "overgrowth-cerulean-soil",
		icon = "__outer_moons__/graphics/icons/overgrowth-cerulean-soil.png",
		subgroup = "terrain",
		order = "c[landfill]-f[overgrowth]",
		inventory_move_sound = item_sounds.landfill_inventory_move,
		pick_sound = item_sounds.landfill_inventory_pickup,
		drop_sound = item_sounds.landfill_inventory_move,
		stack_size = 100,
		default_import_location = "gleba",
		place_as_tile =
		{
		  result = "overgrowth-cerulean-soil",
		  condition_size = 1,
		  condition = {layers={}},
		  tile_condition = { 
			"wetland-light-green-slime",
			"wetland-green-slime",
			"wetland-yumako",
			"lowland-olive-blubber",
			"lowland-olive-blubber-2",
			"lowland-olive-blubber-3",
			"lowland-brown-blubber",
			"lowland-pale-green",
			"natural-yumako-soil",
			"artificial-yumako-soil",
			"wetland-pink-tentacle",
			"wetland-red-tentacle",
			"wetland-jellynut",
			"lowland-red-vein",
			"lowland-red-vein-2",
			"lowland-red-vein-3",
			"lowland-red-vein-4",
			"lowland-red-vein-dead",
			"lowland-red-infection",
			"lowland-cream-red",
			"lowland-cream-cauliflower",
			"lowland-cream-cauliflower-2",
			"natural-jellynut-soil",
			"artificial-jellynut-soil",
			"midland-yellow-crust",
			"midland-yellow-crust-2",
			"midland-yellow-crust-3",
			"midland-yellow-crust-4",
			"artificial-ochre-soil",
			"lowland-dead-skin",
		    "lowland-dead-skin-2",
			"lowland-cream-cauliflower",
		    "lowland-cream-cauliflower-2",
		    "midland-cracked-lichen-dark",
		    "highland-dark-rock",
		    "artificial-cerulean-soil",
			"wetland-light-dead-skin",
		    "wetland-dead-skin",
		    "wetland-blue-slime",
		    "lowland-cream-cauliflower",
		    "lowland-cream-cauliflower-2",
			"artificial-cuticle-soil",
			"gleba-deep-lake",			
			"highland-dark-rock-2",
			"highland-yellow-rock",
		  }
		}
	},
	{
		type = "item",
		name = "artificial-cuticle-soil",
		icon = "__outer_moons__/graphics/icons/artificial-cuticle-soil.png",
		subgroup = "terrain",
		order = "c[landfill]-b[artificial]",
		inventory_move_sound = item_sounds.landfill_inventory_move,
		pick_sound = item_sounds.landfill_inventory_pickup,
		drop_sound = item_sounds.landfill_inventory_move,
		stack_size = 100,
		default_import_location = "gleba",
		place_as_tile =
		{
		  result = "artificial-cuticle-soil",
		  condition_size = 1,
		  condition = {layers={}},
		  tile_condition = {
		    "wetland-light-dead-skin",
		    "wetland-dead-skin",
		    "lowland-cream-cauliflower",
		    "lowland-cream-cauliflower-2",
		  }
		}
	},
	{
		type = "item",
		name = "overgrowth-cuticle-soil",
		icon = "__outer_moons__/graphics/icons/overgrowth-cuticle-soil.png",
		subgroup = "terrain",
		order = "c[landfill]-b[overgrowth]",
		inventory_move_sound = item_sounds.landfill_inventory_move,
		pick_sound = item_sounds.landfill_inventory_pickup,
		drop_sound = item_sounds.landfill_inventory_move,
		stack_size = 100,
		default_import_location = "gleba",
		place_as_tile =
		{
		  result = "overgrowth-cuticle-soil",
		  condition_size = 1,
		  condition = {layers={}},
		  tile_condition = { 
			"wetland-light-green-slime",
			"wetland-green-slime",
			"wetland-yumako",
			"lowland-olive-blubber",
			"lowland-olive-blubber-2",
			"lowland-olive-blubber-3",
			"lowland-brown-blubber",
			"lowland-pale-green",
			"natural-yumako-soil",
			"artificial-yumako-soil",
			"wetland-pink-tentacle",
			"wetland-red-tentacle",
			"wetland-jellynut",
			"lowland-red-vein",
			"lowland-red-vein-2",
			"lowland-red-vein-3",
			"lowland-red-vein-4",
			"lowland-red-vein-dead",
			"lowland-red-infection",
			"lowland-cream-red",
			"lowland-cream-cauliflower",
			"lowland-cream-cauliflower-2",
			"natural-jellynut-soil",
			"artificial-jellynut-soil",
			"midland-yellow-crust",
			"midland-yellow-crust-2",
			"midland-yellow-crust-3",
			"midland-yellow-crust-4",
			"artificial-ochre-soil",
			"lowland-dead-skin",
		    "lowland-dead-skin-2",
			"lowland-cream-cauliflower",
		    "lowland-cream-cauliflower-2",
		    "midland-cracked-lichen-dark",
		    "highland-dark-rock",
		    "artificial-cerulean-soil",
			"wetland-light-dead-skin",
		    "wetland-dead-skin",
		    "wetland-blue-slime",
		    "lowland-cream-cauliflower",
		    "lowland-cream-cauliflower-2",
			"artificial-cuticle-soil",
			"gleba-deep-lake",
			"highland-dark-rock-2",
			"highland-yellow-rock",
		  }
		}
	},
	--Fulgora
	{
        type = "item",
        name = "microplastic",
        group = "intermediate-products",
        icon = "__outer_moons__/graphics/icons/microplastic.png",
        subgroup = "fulgora-processes",
		default_import_location = "fulgora",
        color_hint = { text = "I" },
        order = "a[chemistry-fulgora]-b[microplastic]",
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        stack_size = 200,
        weight = 0.5 * kg
    },
	-- Feronia
	{
		type = "capsule",
		name = "jellynut",
		icon = "__space-age__/graphics/icons/jellynut.png",
		pictures =
		{
		  { size = 64, filename = "__space-age__/graphics/icons/jellynut.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__space-age__/graphics/icons/jellynut-1.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__space-age__/graphics/icons/jellynut-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__space-age__/graphics/icons/jellynut-3.png", scale = 0.5, mipmap_count = 4 },
		},
		subgroup = "feronia-processes",
		order = "b[feronia-agriculture]-b[jellynut]",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		stack_size = 50,
		default_import_location = "feronia",
		weight = 1 * kg,
		spoil_ticks = 60 * minute,
		fuel_category = "chemical",
		fuel_value = "10MJ",
		spoil_result = "spoilage",
		capsule_action = item_effects.jellynut_speed
	},
	{
		type = "item",
		name = "jellynut-seed",
		icon = "__space-age__/graphics/icons/jellynut-seed.png",
		pictures =
		{
		  { size = 64, filename = "__space-age__/graphics/icons/jellynut-seed-1.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__space-age__/graphics/icons/jellynut-seed-2.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__space-age__/graphics/icons/jellynut-seed-3.png", scale = 0.5, mipmap_count = 4 },
		  { size = 64, filename = "__space-age__/graphics/icons/jellynut-seed-4.png", scale = 0.5, mipmap_count = 4 },
		},
		subgroup = "feronia-processes",
		order = "b[seeds]-b[jellynut-seed]",
		plant_result = "jellystem",
		place_result = "jellystem",
		inventory_move_sound = space_age_item_sounds.agriculture_inventory_move,
		pick_sound = space_age_item_sounds.agriculture_inventory_pickup,
		drop_sound = space_age_item_sounds.agriculture_inventory_move,
		stack_size = 10,
		default_import_location = "gleba",
		weight = 10 * kg,
		fuel_category = "chemical",
		fuel_value = "4MJ"
	},
	-- structures
	{
		type = "item",
		name = "convector",
		icon = "__outer_moons__/graphics/icons/convector.png",
		subgroup = "production-machine",
		order = "g[convector]",
		inventory_move_sound = item_sounds.mechanical_inventory_move,
		pick_sound = item_sounds.mechanical_inventory_pickup,
		drop_sound = item_sounds.mechanical_inventory_move,
		place_result = "convector",
		stack_size = 20,
		weight = 50 * kg,
		--random_tint_color = item_tints.iron_rust		
	},
	{
		type = "item",
		name = "adv-assembling-machine",
		icon = "__outer_moons__/graphics/icons/adv-assembler.png",
		subgroup = "production-machine",
		order = "d[adv-assembling-machine]",
		inventory_move_sound = item_sounds.mechanical_inventory_move,
		pick_sound = item_sounds.mechanical_inventory_pickup,
		drop_sound = item_sounds.mechanical_inventory_move,
		place_result = "adv-assembling-machine",
		stack_size = 20,
		weight = 100 * kg,
		--random_tint_color = item_tints.iron_rust		
	},
	{
		type = "item",
		name = "arc-furnace",
		icon = "__outer_moons__/graphics/icons/arc-furnace.png",
		subgroup = "smelting-machine",
		order = "d[arc-furnace]",
		inventory_move_sound = item_sounds.mechanical_inventory_move,
		pick_sound = item_sounds.mechanical_inventory_pickup,
		drop_sound = item_sounds.mechanical_inventory_move,
		place_result = "arc-furnace",
		stack_size = 20,
		weight = 100 * kg,
		--random_tint_color = item_tints.iron_rust		
	},
	{
		type = "item",
		name = "megafoundry",
		icon = "__outer_moons__/graphics/icons/megafoundry.png",
		subgroup = "smelting-machine",
		order = "e[megafoundry]",
		inventory_move_sound = item_sounds.mechanical_inventory_move,
		pick_sound = item_sounds.mechanical_inventory_pickup,
		drop_sound = item_sounds.mechanical_inventory_move,
		place_result = "megafoundry",
		stack_size = 10,
		weight = 200 * kg,
		--random_tint_color = item_tints.iron_rust		
	},
	
	-- Science
	{
		type = "tool",
		name = "lunar-science-pack",
		localised_description = {"item-description.science-pack"},
		icon = "__outer_moons__/graphics/icons/lunar-science-pack.png",
		subgroup = "science-pack",
		color_hint = { text = "M" },
		order = "h",
		inventory_move_sound = item_sounds.science_inventory_move,
		pick_sound = item_sounds.science_inventory_pickup,
		drop_sound = item_sounds.science_inventory_move,
		stack_size = 200,
		default_import_location = "selene",
		weight = 1*kg,
		durability = 1,
		durability_description_key = "description.science-pack-remaining-amount-key",
		factoriopedia_durability_description_key = "description.factoriopedia-science-pack-remaining-amount-key",
		durability_description_value = "description.science-pack-remaining-amount-value",
		random_tint_color = item_tints.bluish_science
	},
	
	--- TRANSPORT BELTS
	-- OVERWRITE
	{
    type = "item",
    name = "turbo-transport-belt",
    icon = "__outer_moons__/graphics/icons/turbo-transport-belt.png",
    subgroup = "belt",
    color_hint = { text = "4" },
    order = "a[transport-belt]-d[turbo-transport-belt]",
    inventory_move_sound = item_sounds.transport_belt_inventory_move,
    pick_sound = item_sounds.transport_belt_inventory_pickup,
    drop_sound = item_sounds.transport_belt_inventory_move,
    place_result = "turbo-transport-belt",
    stack_size = 100,
    default_import_location = "vulcanus",
    weight = 20*kg
  },
  {
    type = "item",
    name = "turbo-underground-belt",
    icon = "__outer_moons__/graphics/icons/turbo-underground-belt.png",
    subgroup = "belt",
    color_hint = { text = "4" },
    order = "b[underground-belt]-d[turbo-underground-belt]",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "turbo-underground-belt",
    stack_size = 50,
    default_import_location = "vulcanus",
    weight = 40*kg
  },
  {
    type = "item",
    name = "turbo-splitter",
    icon = "__outer_moons__/graphics/icons/turbo-splitter.png",
    subgroup = "belt",
    color_hint = { text = "4" },
    order = "c[splitter]-d[turbo-splitter]",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "turbo-splitter",
    stack_size = 50,
    default_import_location = "vulcanus",
    weight = 40*kg
  },
  {
    type = "item",
    name = "turbo-loader",
    icon = "__outer_moons__/graphics/icons/turbo-loader.png",
    hidden = true,
    subgroup = "belt",
    color_hint = { text = "4" },
    order = "d[loader]-d[turbo-loader]",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "turbo-loader",
    stack_size = 50
  },
  {
    type = "item",
    name = "hyper-transport-belt",
    icon = "__outer_moons__/graphics/icons/hyper-transport-belt.png",
    subgroup = "belt",
    color_hint = { text = "5" },
    order = "a[transport-belt]-e[hyper-transport-belt]",
    inventory_move_sound = item_sounds.transport_belt_inventory_move,
    pick_sound = item_sounds.transport_belt_inventory_pickup,
    drop_sound = item_sounds.transport_belt_inventory_move,
    place_result = "hyper-transport-belt",
    stack_size = 100,
    default_import_location = "mefitis",
    weight = 20*kg
  },
  {
    type = "item",
    name = "hyper-underground-belt",
    icon = "__outer_moons__/graphics/icons/hyper-underground-belt.png",
    subgroup = "belt",
    color_hint = { text = "5" },
    order = "b[underground-belt]-e[hyper-underground-belt]",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "hyper-underground-belt",
    stack_size = 50,
    default_import_location = "mefitis",
    weight = 40*kg
  },
  {
    type = "item",
    name = "hyper-splitter",
    icon = "__outer_moons__/graphics/icons/hyper-splitter.png",
    subgroup = "belt",
    color_hint = { text = "5" },
    order = "c[splitter]-e[hyper-splitter]",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "hyper-splitter",
    stack_size = 50,
    default_import_location = "mefitis",
    weight = 40*kg
  },
  {
    type = "item",
    name = "hyper-loader",
    icon = "__outer_moons__/graphics/icons/hyper-loader.png",
    hidden = true,
    subgroup = "belt",
    color_hint = { text = "5" },
    order = "d[loader]-e[hyper-loader]",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "hyper-loader",
    stack_size = 50
  },
  {
    type = "item",
    name = "vacuum-transport-belt",
    icon = "__outer_moons__/graphics/icons/vacuum-transport-belt.png",
    subgroup = "belt",
    color_hint = { text = "6" },
    order = "a[transport-belt]-f[vacuum-transport-belt]",
    inventory_move_sound = item_sounds.transport_belt_inventory_move,
    pick_sound = item_sounds.transport_belt_inventory_pickup,
    drop_sound = item_sounds.transport_belt_inventory_move,
    place_result = "vacuum-transport-belt",
    stack_size = 100,
    default_import_location = "mefitis",
    weight = 20*kg
  },
  {
    type = "item",
    name = "vacuum-underground-belt",
    icon = "__outer_moons__/graphics/icons/vacuum-underground-belt.png",
    subgroup = "belt",
    color_hint = { text = "6" },
    order = "b[underground-belt]-f[vacuum-underground-belt]",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "vacuum-underground-belt",
    stack_size = 50,
    default_import_location = "mefitis",
    weight = 40*kg
  },
  {
    type = "item",
    name = "vacuum-splitter",
    icon = "__outer_moons__/graphics/icons/vacuum-splitter.png",
    subgroup = "belt",
    color_hint = { text = "6" },
    order = "c[splitter]-f[vacuum-splitter]",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "vacuum-splitter",
    stack_size = 50,
    default_import_location = "mefitis",
    weight = 40*kg
  },
  {
    type = "item",
    name = "vacuum-loader",
    icon = "__outer_moons__/graphics/icons/vacuum-loader.png",
    hidden = true,
    subgroup = "belt",
    color_hint = { text = "6" },
    order = "d[loader]-f[vacuum-loader]",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "vacuum-loader",
    stack_size = 50
  },
  --
  
})
