local item_sounds = require("__base__.prototypes.item_sounds")
local meld = require("meld")

---Creates a basic item
---@param name string name of the item
---@param stack_size integer? The stack size of the item
---@param weight integer? The weight of the item
---@param glow boolean? Does this item glow?
---@param size int? The size of the icon image
---@param extra table? Extra parameters to set?
---@return table
local function quick_item(name, stack_size, weight, glow, extra)
    return meld({
        type = "item",
        name = name,
        subgroup = "intermediate-product",
        stack_size = stack_size or 100,
        icon = "__outer_moons__/graphics/icons/" .. name .. ".png",
        pictures = {
            size = 64,
            filename = "__outer_moons__/graphics/icons/" .. name .. ".png",
            scale = 0.5,
            draw_as_glow = glow or false,
        },
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        weight = weight or (2 * kg)
    }, extra or {})
end

--local bioluminescent_science_pack = meld(
--    table.deepcopy(data.raw["tool"]["automation-science-pack"]), {
--        name = "bioluminescent-science-pack",
--        icon = "__outer_moons__/graphics/icons/bioluminescent-science-pack.png",
--        order = "k[bioluminescent_science_pack]",
--        pictures = meld.overwrite {
--            scale = 0.5,
--            size = 64,
--            filename = "__outer_moons__/graphics/icons/bioluminescent-science-pack.png",
--            draw_as_glow = true,
--    }
--})

data:extend({
	-- Nauvis et al
	{
		type = "item",
		name = "rocket-part-new",
		icon = "__outer_moons__/graphics/icons/rocket-part-new.png",
		subgroup = "intermediate-product",
		order = "d[rocket-parts]-c[rocket-part-new]",
		inventory_move_sound = item_sounds.mechanical_inventory_move,
		pick_sound = item_sounds.mechanical_inventory_pickup,
		drop_sound = item_sounds.mechanical_inventory_move,
		stack_size = 20,
		weight = 20*kg,
	},
	-- Selene
	{
        type = "item",
        name = "metallic-regolith",
        group = "intermediate-products",
        icon = "__outer_moons__/graphics/icons/regolith.png",
        pictures =
        {
            size = 64,
            filename = "__outer_moons__/graphics/icons/regolith.png",
            scale = 0.5,
            mipmap_count = 4,
        },
        subgroup = "selene-processes",
		default_import_location = "selene",
        color_hint = { text = "I" },
        order = "b[selene]-a[regolith]",
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        stack_size = 200,
        weight = 1 * kg
    },
	{
        type = "item",
        name = "aluminum-ore",
        group = "intermediate-products",
        icon = "__outer_moons__/graphics/icons/aluminum-ore.png",
        pictures =
        {
            size = 64,
            filename = "__outer_moons__/graphics/icons/aluminum-ore.png",
            scale = 0.5,
            mipmap_count = 4,
        },
        subgroup = "selene-processes",
		default_import_location = "selene",
        color_hint = { text = "I" },
        order = "b[selene]-b[aluminum-ore]",
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        stack_size = 50,
        weight = 5 * kg
    },
    {
        type = "item",
        name = "titanium-ore",
        group = "intermediate-products",
        icon = "__outer_moons__/graphics/icons/titanium-ore.png",
        pictures =
        {
            size = 64,
            filename = "__outer_moons__/graphics/icons/titanium-ore.png",
            scale = 0.5,
            mipmap_count = 4,
        },
        subgroup = "selene-processes",
		default_import_location = "selene",
        color_hint = { text = "I" },
        order = "b[selene]-c[titanium-ore]",
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        stack_size = 50,
        weight = 10 * kg
    },
	{
		type = "item",
		name = "titanium-plate",		
        group = "intermediate-products",
		icon = "__outer_moons__/graphics/icons/titanium-plate.png",
		subgroup = "selene-processes",
		order = "g[titanium-plate]",
		inventory_move_sound = item_sounds.metal_small_inventory_move,
		pick_sound = item_sounds.metal_small_inventory_pickup,
		drop_sound = item_sounds.metal_small_inventory_move,
		stack_size = 100,
		weight = 10 * kg,
	},
	{
		type = "item",
		name = "lye",		
        group = "intermediate-products",
		icon = "__outer_moons__/graphics/icons/lye.png",
		subgroup = "selene-processes",
		order = "d[lye]",
		inventory_move_sound = item_sounds.sulfur_inventory_move,
		pick_sound = item_sounds.resource_inventory_pickup,
		drop_sound = item_sounds.sulfur_inventory_move,
		stack_size = 200,
		weight = 1 * kg,
	},
	{
		type = "item",
		name = "gibbsite",		
        group = "intermediate-products",
		icon = "__outer_moons__/graphics/icons/gibbsite.png",
		subgroup = "selene-processes",
		order = "e[gibbsite]",
		inventory_move_sound = item_sounds.sulfur_inventory_move,
		pick_sound = item_sounds.resource_inventory_pickup,
		drop_sound = item_sounds.sulfur_inventory_move,
		stack_size = 200,
		weight = 1 * kg,
	},
	{
		type = "item",
		name = "alumina",		
        group = "intermediate-products",
		icon = "__outer_moons__/graphics/icons/alumina.png",
		subgroup = "selene-processes",
		order = "f[alumina]",
		inventory_move_sound = item_sounds.sulfur_inventory_move,
		pick_sound = item_sounds.resource_inventory_pickup,
		drop_sound = item_sounds.sulfur_inventory_move,
		stack_size = 200,
		weight = 1 * kg,
	},
	{
		type = "item",
		name = "aluminum-plate",		
        group = "intermediate-products",
		icon = "__outer_moons__/graphics/icons/aluminum-plate.png",
		subgroup = "selene-processes",
		order = "g[aluminum-plate]",
		inventory_move_sound = item_sounds.metal_small_inventory_move,
		pick_sound = item_sounds.metal_small_inventory_pickup,
		drop_sound = item_sounds.metal_small_inventory_move,
		stack_size = 100,
		weight = 1 * kg,
	},
	--Fulgora
	{
        type = "item",
        name = "microplastic",
        group = "intermediate-products",
        icon = "__outer_moons__/graphics/icons/microplastic.png",
        subgroup = "fulgora-processes",
		default_import_location = "fulgora",
        color_hint = { text = "I" },
        order = "scrap]-b[microplastic]",
        inventory_move_sound = item_sounds.resource_inventory_move,
        pick_sound = item_sounds.resource_inventory_pickup,
        drop_sound = item_sounds.resource_inventory_move,
        stack_size = 200,
        weight = 1 * kg
    },
	-- structures
	{
		type = "item",
		name = "convector",
		icon = "__outer_moons__/graphics/icons/convector.png",
		subgroup = "production-machine",
		color_hint = { text = "1" },
		order = "g[convector]",
		inventory_move_sound = item_sounds.mechanical_inventory_move,
		pick_sound = item_sounds.mechanical_inventory_pickup,
		drop_sound = item_sounds.mechanical_inventory_move,
		place_result = "convector",
		stack_size = 20,
		weight = 50 * kg,
		--random_tint_color = item_tints.iron_rust		
	},
	{
		type = "item",
		name = "adv-assembling-machine",
		icon = "__outer_moons__/graphics/icons/adv-assembler.png",
		subgroup = "production-machine",
		color_hint = { text = "1" },
		order = "d[adv-assembling-machine]",
		inventory_move_sound = item_sounds.mechanical_inventory_move,
		pick_sound = item_sounds.mechanical_inventory_pickup,
		drop_sound = item_sounds.mechanical_inventory_move,
		place_result = "adv-assembling-machine",
		stack_size = 20,
		weight = 100 * kg,
		--random_tint_color = item_tints.iron_rust		
	},
	{
		type = "item",
		name = "arc-furnace",
		icon = "__outer_moons__/graphics/icons/arc-furnace.png",
		subgroup = "smelting-machine",
		color_hint = { text = "1" },
		order = "d[arc-furnace]",
		inventory_move_sound = item_sounds.mechanical_inventory_move,
		pick_sound = item_sounds.mechanical_inventory_pickup,
		drop_sound = item_sounds.mechanical_inventory_move,
		place_result = "arc-furnace",
		stack_size = 20,
		weight = 100 * kg,
		--random_tint_color = item_tints.iron_rust		
	},
	
	-- Science
	{
		type = "tool",
		name = "lunar-science-pack",
		localised_description = {"item-description.science-pack"},
		icon = "__outer_moons__/graphics/icons/lunar-science-pack.png",
		subgroup = "science-pack",
		color_hint = { text = "M" },
		order = "h",
		inventory_move_sound = item_sounds.science_inventory_move,
		pick_sound = item_sounds.science_inventory_pickup,
		drop_sound = item_sounds.science_inventory_move,
		stack_size = 200,
		default_import_location = "selene",
		weight = 1*kg,
		durability = 1,
		durability_description_key = "description.science-pack-remaining-amount-key",
		factoriopedia_durability_description_key = "description.factoriopedia-science-pack-remaining-amount-key",
		durability_description_value = "description.science-pack-remaining-amount-value",
		random_tint_color = item_tints.bluish_science
	},
	
	--- TRANSPORT BELTS
	-- OVERWRITE
	{
    type = "item",
    name = "turbo-transport-belt",
    icon = "__outer_moons__/graphics/icons/turbo-transport-belt.png",
    subgroup = "belt",
    color_hint = { text = "4" },
    order = "a[transport-belt]-d[turbo-transport-belt]",
    inventory_move_sound = item_sounds.transport_belt_inventory_move,
    pick_sound = item_sounds.transport_belt_inventory_pickup,
    drop_sound = item_sounds.transport_belt_inventory_move,
    place_result = "turbo-transport-belt",
    stack_size = 100,
    default_import_location = "vulcanus",
    weight = 20*kg
  },
  {
    type = "item",
    name = "turbo-underground-belt",
    icon = "__outer_moons__/graphics/icons/turbo-underground-belt.png",
    subgroup = "belt",
    color_hint = { text = "4" },
    order = "b[underground-belt]-d[turbo-underground-belt]",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "turbo-underground-belt",
    stack_size = 50,
    default_import_location = "vulcanus",
    weight = 40*kg
  },
  {
    type = "item",
    name = "turbo-splitter",
    icon = "__outer_moons__/graphics/icons/turbo-splitter.png",
    subgroup = "belt",
    color_hint = { text = "4" },
    order = "c[splitter]-d[turbo-splitter]",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "turbo-splitter",
    stack_size = 50,
    default_import_location = "vulcanus",
    weight = 40*kg
  },
  {
    type = "item",
    name = "turbo-loader",
    icon = "__outer_moons__/graphics/icons/turbo-loader.png",
    hidden = true,
    subgroup = "belt",
    color_hint = { text = "4" },
    order = "d[loader]-d[turbo-loader]",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "turbo-loader",
    stack_size = 50
  },
  {
    type = "item",
    name = "hyper-transport-belt",
    icon = "__outer_moons__/graphics/icons/hyper-transport-belt.png",
    subgroup = "belt",
    color_hint = { text = "5" },
    order = "a[transport-belt]-e[hyper-transport-belt]",
    inventory_move_sound = item_sounds.transport_belt_inventory_move,
    pick_sound = item_sounds.transport_belt_inventory_pickup,
    drop_sound = item_sounds.transport_belt_inventory_move,
    place_result = "hyper-transport-belt",
    stack_size = 100,
    default_import_location = "mefitis",
    weight = 20*kg
  },
  {
    type = "item",
    name = "hyper-underground-belt",
    icon = "__outer_moons__/graphics/icons/hyper-underground-belt.png",
    subgroup = "belt",
    color_hint = { text = "5" },
    order = "b[underground-belt]-e[hyper-underground-belt]",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "hyper-underground-belt",
    stack_size = 50,
    default_import_location = "mefitis",
    weight = 40*kg
  },
  {
    type = "item",
    name = "hyper-splitter",
    icon = "__outer_moons__/graphics/icons/hyper-splitter.png",
    subgroup = "belt",
    color_hint = { text = "5" },
    order = "c[splitter]-e[hyper-splitter]",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "hyper-splitter",
    stack_size = 50,
    default_import_location = "mefitis",
    weight = 40*kg
  },
  {
    type = "item",
    name = "hyper-loader",
    icon = "__outer_moons__/graphics/icons/hyper-loader.png",
    hidden = true,
    subgroup = "belt",
    color_hint = { text = "5" },
    order = "d[loader]-e[hyper-loader]",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "hyper-loader",
    stack_size = 50
  },
  {
    type = "item",
    name = "vacuum-transport-belt",
    icon = "__outer_moons__/graphics/icons/vacuum-transport-belt.png",
    subgroup = "belt",
    color_hint = { text = "6" },
    order = "a[transport-belt]-f[vacuum-transport-belt]",
    inventory_move_sound = item_sounds.transport_belt_inventory_move,
    pick_sound = item_sounds.transport_belt_inventory_pickup,
    drop_sound = item_sounds.transport_belt_inventory_move,
    place_result = "vacuum-transport-belt",
    stack_size = 100,
    default_import_location = "mefitis",
    weight = 20*kg
  },
  {
    type = "item",
    name = "vacuum-underground-belt",
    icon = "__outer_moons__/graphics/icons/vacuum-underground-belt.png",
    subgroup = "belt",
    color_hint = { text = "6" },
    order = "b[underground-belt]-f[vacuum-underground-belt]",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "vacuum-underground-belt",
    stack_size = 50,
    default_import_location = "mefitis",
    weight = 40*kg
  },
  {
    type = "item",
    name = "vacuum-splitter",
    icon = "__outer_moons__/graphics/icons/vacuum-splitter.png",
    subgroup = "belt",
    color_hint = { text = "6" },
    order = "c[splitter]-f[vacuum-splitter]",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "vacuum-splitter",
    stack_size = 50,
    default_import_location = "mefitis",
    weight = 40*kg
  },
  {
    type = "item",
    name = "vacuum-loader",
    icon = "__outer_moons__/graphics/icons/vacuum-loader.png",
    hidden = true,
    subgroup = "belt",
    color_hint = { text = "6" },
    order = "d[loader]-f[vacuum-loader]",
    inventory_move_sound = item_sounds.mechanical_inventory_move,
    pick_sound = item_sounds.mechanical_inventory_pickup,
    drop_sound = item_sounds.mechanical_inventory_move,
    place_result = "vacuum-loader",
    stack_size = 50
  },
})
